### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by avocraft** [xmclark/zeebest#25]
The last change was made 4 months ago, Since then there have been some changes made on zeebe itself like error handling and other improvements. Any signs on updating the rust client as well?

**Comment by xmclark** [comment]
Hi @avocraft. This project is not actively maintained.

Although the zeebe maintainers were super supportive of this project, It was just me working on it and I wasn’t getting any new involvement from the community. I started this project to help me learn some new features of rust, and experiment with zeebe. I also love workflows, and love the zeebe architecture.

I have a pretty epic vision for this library. I sunk a ton of hours into a re-write to solve some of the problems you mention, but I decided to stop working on zeebest for a couple reasons:

1. the rust async ecosystem is a complete mess and doesn’t appear to be getting any better. There is a stark split between async-std and tokio that prevents libraries like this one from being compatible across async runtimes. I burnt my emotional capacity trying to participate in Rust open source, and have decided to simply step away for a little while to recharge.
2. I became incredibly discouraged by Camunda’s licensing choices applied in late 2019 to the zeebe components. Camunda has good intentions and is trying to defend itself from the big clouds and ensure people pay for usage of their amazing software. Unfortunately, those choices would make it really hard for me to rationalize using zeebe in new projects.

I have a vision for this library and would be happy to revisit development if someone was interested in helping me 😊. Happy to talk here or offline about things more.

**Comment by avocraft** [comment]
Hey @xmclark thanks for clarifying things and thank you for all your hard work you put in this project! I suppose Golang/JavaScript clients is the way to go then. 

Curious on the licensing issues I have been completely out of loop on that one, will do some research but I was not aware on any issues.

**Comment by xmclark** [comment]
[This page does an excellent job of explaining the different licenses.](https://zeebe.io/zeebe-license-overview/)

I recommend reading the [Zeebe Community License](https://zeebe.io/legal/zeebe-community-license-1.0/) and I'd also recommend you read about the requirements for using Camunda Operate (a generally necessary component for any zeebe install) *in production*.
